name: 笑いのツボ
description: ユーモアでマッチング
full_description: 'A more complete description of the app<br>
<br>With a lot of features:
<br>- 特徴 1
<br>- 特徴 2
<br>- 特徴 3'
android: https://telegra.ph/Replace-this-link-07-23
iOS: https://telegra.ph/Replace-this-link-07-23
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
companies:
  - url: https://telegra.ph/Replace-this-link-07-23
    image: androidpolice.png
    
